# Generated by Django 2.0.1 on 2018-05-06 11:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=255, unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
        ),
    ]
