# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-15 11:06
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcpt', models.CharField(default='', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name={})),
            ],
        ),
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyType'),
        ),
    ]
