# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 17, 11, 17, 1, 188614, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 17, 11, 17, 6, 972658, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
