# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20180117_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytype',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
